#!/bin/bash

# Скрипт установки FRP клиента

set -e

# Параметры для вашего варианта
SERVER_ADDR="course.prafdin.ru"
AUTH_TOKEN="devops"
USERNAME="zhirnov"

echo "🚀 Установка FRP клиента..."
echo "📋 Параметры:"
echo "   Сервер: $SERVER_ADDR"
echo "   Токен: $AUTH_TOKEN"
echo "   Пользователь: $USERNAME"
echo ""

# Проверяем права суперпользователя
if [[ $EUID -ne 0 ]]; then
   echo "❌ Этот скрипт должен запускаться с правами root (sudo)"
   exit 1
fi

# Создаем директорию для FRP
mkdir -p /etc/frp
mkdir -p /var/log/frp

if command -v frpc >/dev/null 2>&1; then
   echo "✅ FRP клиент (frpc) уже установлен"
else
   echo "📥 Скачиваем и устанавливаем FRP как systemd сервис..."
   curl -fsSL https://gist.github.com/lawrenceching/41244a182307940cc15b45e3c4997346/raw/0576ea85d898c965c3137f7c38f9815e1233e0d1/install-frp-as-systemd-service.sh | bash
fi

# Генерируем конфигурацию
echo "⚙️  Генерируем конфигурацию..."
cat > /etc/frp/frpc.toml << EOC
# FRP Client Configuration - Generated by install-frp.sh

serverAddr = "$SERVER_ADDR"
serverPort = 7000

auth.method = "token"
auth.token = "$AUTH_TOKEN"

# Прокси для webhook сервера
[[proxies]]
name = "hook-$USERNAME"
type = "http"
localIP = "127.0.0.1"
localPort = 8080
customDomains = ["webhook.$USERNAME.$SERVER_ADDR"]

# Прокси для веб-приложения
[[proxies]]
name = "app-$USERNAME"
type = "http"
localIP = "127.0.0.1"
localPort = 8181
customDomains = ["app.$USERNAME.$SERVER_ADDR"]
EOC

echo "✅ Конфигурация сгенерирована в /etc/frp/frpc.toml"

# Устанавливаем права доступа
chown -R root:root /etc/frp
chmod 644 /etc/frp/frpc.toml

echo "🔧 Перезагружаем systemd и запускаем FRP клиент..."
systemctl daemon-reload
systemctl enable frpc
systemctl restart frpc

echo "📊 Проверяем статус FRP клиента..."
systemctl status frpc --no-pager

echo ""
echo "✅ FRP клиент установлен и запущен!"
echo ""
echo "🌐 URLs для вашей конфигурации:"
echo "   Webhook URL: http://webhook.zhirnov.course.prafdin.ru"
echo "   App URL: http://app.zhirnov.course.prafdin.ru"
